---
abstract: 'Use VLC libraries'
author:
  - 'Alexey Sokolov <alexey@alexeysokolov.co.cc>'
build_requires:
  Archive::Extract: 0
  Archive::Tar: 0
  Archive::Zip: 0
  Digest::SHA: 0
  ExtUtils::CBuilder: 0
  File::Fetch: 0.24
  File::Find: 0
  File::Path: 2.08
  File::ShareDir: 0
  File::Spec: 0
  File::Temp: 0
  File::Which: 0
  Module::Build: 0.36
  Text::Patch: 1.4
configure_requires:
  Archive::Extract: 0
  Capture::Tiny: 0.11
  Digest::SHA: 0
  ExtUtils::PkgConfig: 0
  File::Fetch: 0.24
  File::Find: 0
  File::Path: 2.08
  File::ShareDir: 0
  File::Spec: 0
  File::Which: 0
  Module::Build: 0.36
  Text::Patch: 1.4
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-VideoLAN-LibVLC
provides:
  Alien::VideoLAN::LibVLC:
    file: lib/Alien/VideoLAN/LibVLC.pm
    version: 0.0_5
requires:
  Capture::Tiny: 0.11
  Carp: 0
  ExtUtils::CBuilder: 0
  ExtUtils::PkgConfig: 0
  File::ShareDir: 1.00
  File::Spec: 0
  File::Temp: 0
  File::Which: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.0_5
